//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ROS
{
    [Serializable]
    public class Ultra_sonicMsg : Message
    {
        public const string k_RosMessageName = "ROS/ultra_sonic";
        public override string RosMessageName => k_RosMessageName;

        public float distance;
        public bool interrupt;

        public Ultra_sonicMsg()
        {
            this.distance = 0.0f;
            this.interrupt = false;
        }

        public Ultra_sonicMsg(float distance, bool interrupt)
        {
            this.distance = distance;
            this.interrupt = interrupt;
        }

        public static Ultra_sonicMsg Deserialize(MessageDeserializer deserializer) => new Ultra_sonicMsg(deserializer);

        private Ultra_sonicMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.distance);
            deserializer.Read(out this.interrupt);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.distance);
            serializer.Write(this.interrupt);
        }

        public override string ToString()
        {
            return "Ultra_sonicMsg: " +
            "\ndistance: " + distance.ToString() +
            "\ninterrupt: " + interrupt.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
